name: frpc-amd64
on:
  push:
    branches:
      - master  
    tags:
      - '*'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frpc/amd64
          platforms: linux/amd64
          push: true
          tags: |
            snowdreamtechamd64/frpc:latest
            snowdreamtechamd64/frpc:0.54.0
            ghcr.io/snowdreamtech/frpc:amd64-latest
            ghcr.io/snowdreamtech/frpc:amd64-0.54.0            